Add TCP Reuse Port and TLS1.3 Ciphersuites Customize Feature
trojan-gfw/trojan pull request #177
Opened 2019-12-12 16:54 UTC by xsm1997

1. Add TCP reuse port feature. This allow user to start multiple instance of Trojan and should improve TCP throughput on multi-core systems.
2. Add TLS1.3 ciphersuites customize feature. Trojan used to only be able to customize TLS1.2 ciphers. This feature allow user to customize TLS1.3 ciphersuite with OpenSSL >= 1.1.1 compiled.

2019-12-12 16:55 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trojan-gfw/trojan?pullRequest=177) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trojan-gfw/trojan?pullRequest=177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trojan-gfw/trojan?pullRequest=177) it.</sub>

2019-12-12 16:57 UTC, GreaterFire commented
@xsm1997 I'll get back to you late December due to IRL responsibilities. But TCP port reuse is by default enabled just a few lines above your code.

2019-12-12 16:59 UTC, GreaterFire commented
@xsm1997 Also, I believe that you can set TLS 1.3 ciphersuite with SSL_CTX_set_cipher_list

2019-12-12 17:01 UTC, xsm1997 commented
> @xsm1997 I'll get back to you late December due to IRL responsibilities. But TCP port reuse is by default enabled just a few lines above your code.

You enabled TCP address reuse, not port reuse, as far as I see.

2019-12-12 17:02 UTC, xsm1997 commented
> @xsm1997 Also, I believe that you can set TLS 1.3 ciphersuite with SSL_CTX_set_cipher_list

Unfortunately, No. You cannot set TLS 1.3 ciphersuite using SSL_CTX_set_cipher_list. It is a different API by OpenSSL documentation. [(Openssl Documentation)](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_ciphersuites.html)

2019-12-14 11:35 UTC, zhangsan946 commented
@GreaterFire 大火兄，请review一下pr，merge一下撒~

2019-12-20 20:05 UTC, GreaterFire requested changes
Code looks very good to me! In addition to the comments, can you also add these 2 config options to examples and tests?
Once you sign the CLA I'll merge it.

2019-12-20 20:05 UTC, GreaterFire commented on docs/config.md
> +        "reuse_port": false,
Add this also to other config types.

2019-12-20 20:05 UTC, GreaterFire commented on src/core/config.h
> +        bool reuse_port;
Move it up between `keep_alive` and `fast_open`.

2019-12-20 20:05 UTC, GreaterFire commented on src/core/config.cpp
> +    tcp.reuse_port = tree.get("tcp.reuse_port", false);
Move it up between keep_alive and fast_open.

2019-12-20 20:05 UTC, GreaterFire commented on src/core/service.cpp
> +#endif
```suggestion
#endif // ENABLE_REUSE_PORT
```

2019-12-20 20:05 UTC, GreaterFire commented on src/core/service.cpp
> +#else
```suggestion
#else // ENABLE_REUSE_PORT
```

2019-12-20 20:05 UTC, GreaterFire commented on src/core/service.cpp
> +#endif
```suggestion
#endif // ENABLE_REUSE_PORT
```

2019-12-20 20:05 UTC, GreaterFire commented on src/core/service.cpp
> +        Log::log_with_date_time("TLS1.3 ciphersuites is not supported", Log::WARN);
```suggestion
        Log::log_with_date_time("TLS1.3 ciphersuites are not supported", Log::WARN);
```

2019-12-22 12:13 UTC, wongsyrone commented on src/core/service.cpp
> +#endif
I suggest

```cpp
    if (config.ssl.cipher_tls13 != "") {
#ifdef ENABLE_TLS13_CIPHERSUITES
        SSL_CTX_set_ciphersuites(native_context, config.ssl.cipher_tls13.c_str());
#else
        Log::log_with_date_time("TLS1.3 ciphersuites are not supported", Log::WARN);
#endif
    }
```

2019-12-22 12:15 UTC, wongsyrone commented on src/core/service.cpp
> +#endif
BTW, you'd better add comments for these preprocessor if directives
```cpp
    if (config.ssl.cipher_tls13 != "") {
#ifdef ENABLE_TLS13_CIPHERSUITES
        SSL_CTX_set_ciphersuites(native_context, config.ssl.cipher_tls13.c_str());
#else  // ENABLE_TLS13_CIPHERSUITES
        Log::log_with_date_time("TLS1.3 ciphersuites are not supported", Log::WARN);
#endif // ENABLE_TLS13_CIPHERSUITES
    }
```

2019-12-22 12:48 UTC, wongsyrone commented on src/core/service.cpp
> +#endif // ENABLE_REUSE_PORT
Please fold preprocessor if directives into the if clause as cipher_tls13.

2019-12-22 22:37 UTC, wongsyrone commented
Can you add <SOL_SOCKET, SO_REUSEADDR> , it's pretty like SO_REUSEPORT, just put the option above the current so_reuseport.

http://man7.org/linux/man-pages/man7/socket.7.html

2019-12-23 04:08 UTC, xsm1997 commented
@wongsyrone SO_REUSEADDR is already enabled a few lines above using the boost built-in way.

2019-12-23 06:20 UTC, wongsyrone approved these changes
LGTM now.

2019-12-27 02:46 UTC, GreaterFire approved these changes
LGTM! Thanks!

2019-12-27 02:46 UTC, GreaterFire commented on CMakeLists.txt
> +    if (ENABLE_REUSE_PORT)
```suggestion
    if(ENABLE_REUSE_PORT)
```

2019-12-27 02:48 UTC, merged